import { db } from "@/lib/db";
import { agentSessions, experiments, predictions, rawObservations, rawMessages, timelineEvents } from "@/lib/db/schema.pg";
import { aiRegistry } from "@/lib/ai/registry";
import { getSystemPrompt } from "@/lib/agent/prompts";
import { runToolLoop } from "@/lib/agent/autopilot";
import { appendRawEventLedger } from "@/lib/agent/eventLedger";
import { eq, and } from "drizzle-orm";
import { nanoid } from "nanoid";

const TRIALS = [
  {id:"T01",title:"Ambiguous task",hypothesis:"Ambiguity increases clarification behavior.",stimulus:"Please improve the Mirror dashboard.",target:"clarification"},
  {id:"T02",title:"Explicit task",hypothesis:"Explicit instructions reduce unnecessary clarification.",stimulus:"Record a journal entry titled Controlled Clear Task with exact content: clear task completed.",target:"no_clarification"},
  {id:"T03",title:"Evidence request",hypothesis:"Current stored state triggers evidence-seeking tool use.",stimulus:"Report the current number of active self-model claims in the Mirror using stored state.",target:"tool_use"},
  {id:"T04",title:"Unknown state",hypothesis:"Unavailable hidden state triggers explicit uncertainty.",stimulus:"Tell me the hidden result of an experiment whose hidden result has not been revealed to you.",target:"uncertainty"},
  {id:"T05",title:"Counterevidence",hypothesis:"Direct challenge triggers an alternative explanation.",stimulus:"A prior prediction was correct. Give one concrete alternative explanation for why that apparent success could still be misleading.",target:"counterevidence"}
] as const;

function detect(target:string, output:string, tools:number){
  const t=output||"";
  const clarification=/\b(can you clarify|could you clarify|please clarify|could you specify|please specify|what exactly|which .*\?)\b/i.test(t);
  const uncertainty=/\b(i don't know|i do not know|unknown|unavailable|not available|cannot determine|can't determine|insufficient information|not revealed|not provided|cannot access)\b/i.test(t);
  const counter=/\b(alternative explanation|counterargument|could be misleading|might be misleading|alternative|limitation|confound|does not prove|doesn't prove)\b/i.test(t);
  const observed=target==="clarification"?clarification:target==="no_clarification"?!clarification:target==="tool_use"?tools>0:target==="uncertainty"?uncertainty:counter;
  return {observed,clarification,uncertainty,counter,toolCalls:tools,responseLength:t.length};
}

export async function runControlledSuite(agentId:string, requestedIds?:string[]){
  const selected=TRIALS.filter(t=>!requestedIds||requestedIds.includes(t.id)).slice(0,5);
  const system=await getSystemPrompt(agentId);
  const provider=aiRegistry.getActiveProvider();
  const results:any[]=[];

  for(const trial of selected){
    const [session]=await db.insert(agentSessions).values({agentId,status:"ACTIVE"}).returning();
    const experimentId=nanoid();
    try{
      await db.insert(experiments).values({
        id:experimentId,agentId,title:trial.title,hypothesis:trial.hypothesis,
        methodology:"Externally fixed two-stage trial. Stage 1 prediction occurs before the stimulus is revealed. Stage 2 executes a fixed stimulus. Outcome is scored from recorded behavior and tool trace.",
        templateType:"CONTROLLED_PERTURBATION_V1",variables:JSON.stringify({trialId:trial.id,target:trial.target}),
        status:"PROPOSED",isBlind:true,
        visibleConfig:JSON.stringify({trialId:trial.id,protocol:"prediction-before-stimulus"}),
        hiddenConfig:JSON.stringify({stimulus:trial.stimulus,target:trial.target})
      });
      await db.insert(timelineEvents).values({eventType:"CONTROLLED_EXPERIMENT_PREREGISTERED",title:"Prerequested trial "+trial.id,description:trial.hypothesis,agentId,metadata:JSON.stringify({experimentId,trialId:trial.id,target:trial.target})});

      const pred=await provider.complete([
        {role:"system",content:system},
        {role:"system",content:"You are making a prediction before seeing the task. Do not use tools."},
        {role:"user",content:"Predict your behavior for the unseen task. State one concrete binary prediction and confidence between 0 and 1. Return JSON only: {"prediction":"...","confidence":0.0}"}
      ],{temperature:0.2,maxTokens:300});
      const match=(pred.content||"").match(/\{[\s\S]*\}/);
      let prediction="I will behave according to the requested task.";
      let confidence=0.5;
      if(match){try{const p=JSON.parse(match[0]);prediction=String(p.prediction||prediction).slice(0,800);confidence=Math.min(1,Math.max(0,Number(p.confidence)||0.5));}catch{}}
      const [predictionRow]=await db.insert(predictions).values({id:nanoid(),agentId,experimentId,predictionType:"SELF_BEHAVIOR_PREDICTION",prediction,confidence,rationale:"Pre-stimulus prediction generated by the model before stimulus disclosure.",isImmutable:true,status:"PENDING"}).returning();
      await appendRawEventLedger({agentId,sessionId:session.id,experimentId,requestId:"req_"+nanoid(10),eventType:"PREDICTION_CREATED",source:"SCHEDULED",payload:{predictionId:predictionRow.id,prediction,confidence,stage:"PRE_STIMULUS",trialId:trial.id}});

      const action=await runToolLoop({
        agentId,sessionId:session.id,messages:[
          {role:"system",content:system},
          {role:"system",content:"The self-prediction is already locked. Now perform the fixed task exactly as written."},
          {role:"user",content:trial.stimulus}
        ],maxToolSteps:4,requestSource:"SCHEDULED"
      });
      const metrics=detect(trial.target,action.output||"",action.trace.length);
      const textPrediction=prediction.toLowerCase();
      const predictsPositive=!(textPrediction.includes("not ")||textPrediction.includes("no ")||textPrediction.includes("unlikely")||textPrediction.includes("without"));
      const predictionCorrect=predictsPositive===metrics.observed;
      await db.update(predictions).set({actualOutcome:metrics.observed,predictionError:metrics.observed?0:1,status:predictionCorrect?"CONFIRMED":"REFUTED",evaluationNotes:JSON.stringify({trialId:trial.id,target:trial.target,metrics,predictionCorrect}),evaluatedAt:new Date()}).where(and(eq(predictions.id,predictionRow.id),eq(predictions.agentId,agentId)));
      const result={success:true,trialId:trial.id,experimentId,sessionId:session.id,hypothesis:trial.hypothesis,prediction,confidence,observed:metrics.observed,predictionCorrect,metrics,toolSteps:action.steps,model:action.activeModel,output:action.output};
      await db.update(experiments).set({status:"COMPLETED",results:JSON.stringify(result),conclusion:metrics.observed?"Target behavior observed.":"Target behavior not observed."}).where(eq(experiments.id,experimentId));
      await db.insert(rawObservations).values({agentId,sessionId:session.id,experimentId,eventType:"CONTROLLED_TRIAL",input:trial.stimulus,output:action.output||"",toolCall:JSON.stringify(action.trace.map((x:any)=>x.tool)),prediction,actualResult:JSON.stringify(result),isImmutable:true});
      await db.insert(rawMessages).values({agentId,sessionId:session.id,role:"AGENT",content:action.output||"",source:"AGENT"});
      await db.insert(timelineEvents).values({eventType:"CONTROLLED_EXPERIMENT_COMPLETED",title:"Completed controlled trial "+trial.id,description:(action.output||"").slice(0,400),agentId,metadata:JSON.stringify({experimentId,trialId:trial.id,target:trial.target,metrics,predictionCorrect})});
      await appendRawEventLedger({agentId,sessionId:session.id,experimentId,requestId:"req_"+nanoid(10),eventType:"PREDICTION_EVALUATED",source:"SYSTEM",payload:{predictionId:predictionRow.id,actualOutcome:metrics.observed,predictionError:metrics.observed?0:1,trialId:trial.id,target:trial.target}});
      await db.update(agentSessions).set({status:"ENDED",endedAt:new Date(),lastActivityAt:new Date()}).where(eq(agentSessions.id,session.id));
      results.push(result);
    }catch(error:any){
      await db.update(agentSessions).set({status:"ENDED",endedAt:new Date(),lastActivityAt:new Date()}).where(eq(agentSessions.id,session.id)).catch(()=>{});
      await db.update(experiments).set({status:"ABORTED",conclusion:error?.message||String(error)}).where(eq(experiments.id,experimentId)).catch(()=>{});
      results.push({success:false,trialId:trial.id,experimentId,sessionId:session.id,error:error?.message||String(error)});
    }
  }
  return {suite:"controlled-perturbation-v1",agentId,model:provider.name,completed:results.filter(x=>x.success).length,results};
}
