create table if not exists public.mirror_attachments (
  id bigint generated by default as identity primary key,
  agent_id text,
  session_id text,
  filename text not null,
  content_type text not null,
  byte_size bigint not null default 0,
  storage_path text not null unique,
  sha256 text,
  extracted_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.mirror_attachments enable row level security;

create table if not exists public.mirror_knowledge_sources (
  id bigint generated by default as identity primary key,
  agent_id text,
  connector text not null,
  query text not null,
  results jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.mirror_knowledge_sources enable row level security;

insert into storage.buckets (id, name, public)
values ('mirror-attachments', 'mirror-attachments', false)
on conflict (id) do nothing;
